-- ============================================================================
-- 02_RAW_TABLES.SQL — Raw tables for Revenue Management & Dynamic Pricing
-- Thailand: 120 resort properties across Phuket, Koh Samui, Bangkok, Chiang Mai
-- ============================================================================
USE DATABASE TOURISM_REVENUE;
USE SCHEMA RAW;

-- Core property master (120 properties)
CREATE OR REPLACE TABLE RAW.PROPERTIES (
  PROPERTY_ID VARCHAR(20) NOT NULL,
  PROPERTY_NAME VARCHAR(200),
  DESTINATION VARCHAR(50),          -- Phuket, Koh Samui, Bangkok, Chiang Mai
  CATEGORY VARCHAR(30),             -- Luxury, Upper Upscale, Upscale, Midscale
  ROOMS_TOTAL INT,
  STAR_RATING FLOAT,
  OWNER_GROUP VARCHAR(100),
  LATITUDE FLOAT,
  LONGITUDE FLOAT,
  OPENED_DATE DATE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Reservations (250,000 records, 12 months)
CREATE OR REPLACE TABLE RAW.RESERVATIONS (
  RESERVATION_ID VARCHAR(30) NOT NULL,
  PROPERTY_ID VARCHAR(20),
  GUEST_NATIONALITY VARCHAR(50),
  SOURCE_MARKET VARCHAR(30),        -- China, Europe, US, ASEAN, Korea, Japan, Australia, Domestic
  CHANNEL VARCHAR(30),              -- Direct, Agoda, Booking.com, Expedia, Wholesaler, GDS
  CHECK_IN DATE,
  CHECK_OUT DATE,
  ROOM_NIGHTS INT,
  ADR FLOAT,                        -- Average Daily Rate (THB)
  TOTAL_REVENUE FLOAT,
  STATUS VARCHAR(20),               -- Confirmed, Cancelled, No-Show
  BOOKING_DATE DATE,
  LEAD_TIME_DAYS INT,
  ROOM_TYPE VARCHAR(50),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- OTA competitive rate feeds (500,000 records)
CREATE OR REPLACE TABLE RAW.OTA_RATE_FEEDS (
  FEED_ID VARCHAR(30) NOT NULL,
  PROPERTY_ID VARCHAR(20),
  OTA_NAME VARCHAR(30),             -- Agoda, Booking.com, Expedia, Traveloka, Trip.com
  STAY_DATE DATE,
  ROOM_TYPE VARCHAR(50),
  RATE_THB FLOAT,
  RATE_USD FLOAT,
  AVAILABILITY_STATUS VARCHAR(20),  -- Available, Sold Out, Limited
  SCRAPED_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Demand signals by source market (180,000 records)
CREATE OR REPLACE TABLE RAW.DEMAND_SIGNALS (
  SIGNAL_ID VARCHAR(30) NOT NULL,
  PROPERTY_ID VARCHAR(20),
  SOURCE_MARKET VARCHAR(30),
  SIGNAL_DATE DATE,
  SEARCH_VOLUME INT,                -- Number of searches for this property/market
  BOOKING_INTENT_SCORE FLOAT,       -- 0-100 intent score
  FLIGHT_SEARCHES INT,              -- Inbound flight searches to destination
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Daily revenue actuals (43,800 records = 120 props x 365 days)
CREATE OR REPLACE TABLE RAW.REVENUE_ACTUALS (
  PROPERTY_ID VARCHAR(20),
  REVENUE_DATE DATE,
  ROOMS_AVAILABLE INT,
  ROOMS_SOLD INT,
  ROOM_REVENUE FLOAT,              -- THB
  FB_REVENUE FLOAT,                -- Food & Beverage
  OTHER_REVENUE FLOAT,             -- Spa, excursions, etc.
  TOTAL_REVENUE FLOAT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Competitive set definitions (600 records = 120 props x 5 comps each)
CREATE OR REPLACE TABLE RAW.COMPETITIVE_SET (
  PROPERTY_ID VARCHAR(20),
  COMP_PROPERTY_ID VARCHAR(20),
  COMP_PROPERTY_NAME VARCHAR(200),
  COMP_DESTINATION VARCHAR(50),
  COMP_CATEGORY VARCHAR(30),
  COMP_ROOMS_TOTAL INT,
  COMP_AVG_RATE FLOAT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Inbound flight capacity (3,000 records)
CREATE OR REPLACE TABLE RAW.FLIGHT_CAPACITY (
  ROUTE_ID VARCHAR(30),
  ORIGIN_CITY VARCHAR(100),
  ORIGIN_COUNTRY VARCHAR(50),
  DESTINATION_AIRPORT VARCHAR(10),  -- HKT, USM, BKK, CNX
  AIRLINE VARCHAR(50),
  FLIGHT_DATE DATE,
  SEATS_TOTAL INT,
  SEATS_BOOKED INT,
  LOAD_FACTOR FLOAT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Thailand tourism arrival statistics (monthly by market)
CREATE OR REPLACE TABLE RAW.THAI_TOURISM_STATS (
  STAT_MONTH DATE,
  SOURCE_MARKET VARCHAR(30),
  ARRIVALS INT,
  AVG_LENGTH_OF_STAY FLOAT,
  AVG_SPEND_PER_TRIP FLOAT,        -- THB
  YOY_GROWTH_PCT FLOAT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Strategy documents for Cortex Search (100 documents)
CREATE OR REPLACE TABLE RAW.STRATEGY_DOCS (
  DOC_ID VARCHAR(30) NOT NULL,
  TITLE VARCHAR(300),
  CONTENT VARCHAR(16000),
  DESTINATION VARCHAR(50),
  SEASON VARCHAR(20),               -- High, Shoulder, Low, Songkran, NYE
  MARKET_SEGMENT VARCHAR(50),
  DOC_TYPE VARCHAR(30),             -- Pricing Strategy, Market Brief, Competitor Analysis
  AUTHOR VARCHAR(100),
  PUBLISH_DATE DATE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Landing stage for S3/Kinesis ingestion
CREATE OR REPLACE STAGE RAW.LANDING_STAGE
  FILE_FORMAT = (TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE);
