-- ============================================================================
-- 04_DYNAMIC_TABLES.SQL — Curated layer for Revenue Management & Dynamic Pricing
-- Real aggregation logic producing analytics-ready tables
-- ============================================================================
USE DATABASE TOURISM_REVENUE;
USE SCHEMA CURATED;

-- PROPERTY_REVPAR: Real-time RevPAR with competitive index
CREATE OR REPLACE DYNAMIC TABLE CURATED.PROPERTY_REVPAR
  TARGET_LAG = '5 minutes'
  WAREHOUSE = TOURISM_WH
AS
SELECT
  p.PROPERTY_ID,
  p.PROPERTY_NAME,
  p.DESTINATION,
  p.CATEGORY,
  p.ROOMS_TOTAL,
  ra.REVENUE_DATE,
  ra.ROOMS_SOLD,
  ra.ROOM_REVENUE,
  ra.TOTAL_REVENUE,
  ROUND(ra.ROOM_REVENUE / NULLIF(p.ROOMS_TOTAL, 0), 2) AS REVPAR,
  ROUND(ra.ROOM_REVENUE / NULLIF(ra.ROOMS_SOLD, 0), 2) AS ADR,
  ROUND(ra.ROOMS_SOLD / NULLIF(p.ROOMS_TOTAL, 0), 4) AS OCCUPANCY,
  -- Competitive index: property RevPAR vs average comp set RevPAR (100 = at parity)
  ROUND(
    (ra.ROOM_REVENUE / NULLIF(p.ROOMS_TOTAL, 0)) /
    NULLIF(cs_avg.AVG_COMP_RATE, 0) * 100, 1
  ) AS REVPAR_INDEX
FROM RAW.PROPERTIES p
JOIN RAW.REVENUE_ACTUALS ra ON p.PROPERTY_ID = ra.PROPERTY_ID
LEFT JOIN (
  SELECT
    cs.PROPERTY_ID,
    AVG(cs.COMP_AVG_RATE) AS AVG_COMP_RATE
  FROM RAW.COMPETITIVE_SET cs
  GROUP BY cs.PROPERTY_ID
) cs_avg ON p.PROPERTY_ID = cs_avg.PROPERTY_ID;

-- DEMAND_TIMESERIES: Daily demand index by property+market for ML.FORECAST
CREATE OR REPLACE DYNAMIC TABLE CURATED.DEMAND_TIMESERIES
  TARGET_LAG = '5 minutes'
  WAREHOUSE = TOURISM_WH
AS
SELECT
  ds.PROPERTY_ID || '|' || ds.SOURCE_MARKET AS PROPERTY_MARKET,
  ds.SIGNAL_DATE AS FORECAST_DATE,
  ds.SEARCH_VOLUME + ds.FLIGHT_SEARCHES AS DEMAND_INDEX,
  ds.BOOKING_INTENT_SCORE,
  ds.SOURCE_MARKET,
  p.DESTINATION,
  p.CATEGORY
FROM RAW.DEMAND_SIGNALS ds
JOIN RAW.PROPERTIES p ON ds.PROPERTY_ID = p.PROPERTY_ID;

-- RATE_RECOMMENDATIONS: AI-optimized rate recommendations
CREATE OR REPLACE DYNAMIC TABLE CURATED.RATE_RECOMMENDATIONS
  TARGET_LAG = '5 minutes'
  WAREHOUSE = TOURISM_WH
AS
SELECT
  p.PROPERTY_ID,
  p.PROPERTY_NAME,
  p.DESTINATION,
  ota.STAY_DATE,
  ota.ROOM_TYPE,
  -- Current property rate (our BAR)
  MAX(CASE WHEN ota.OTA_NAME = 'Direct' THEN ota.RATE_THB END) AS OUR_BAR,
  -- Competitor rates
  AVG(CASE WHEN ota.OTA_NAME != 'Direct' THEN ota.RATE_THB END) AS AVG_OTA_RATE,
  MIN(CASE WHEN ota.OTA_NAME != 'Direct' THEN ota.RATE_THB END) AS MIN_OTA_RATE,
  MAX(CASE WHEN ota.OTA_NAME != 'Direct' THEN ota.RATE_THB END) AS MAX_OTA_RATE,
  -- Rate position indicator
  CASE
    WHEN MAX(CASE WHEN ota.OTA_NAME = 'Direct' THEN ota.RATE_THB END) <
         AVG(CASE WHEN ota.OTA_NAME != 'Direct' THEN ota.RATE_THB END) * 0.9
    THEN 'UNDERPRICED'
    WHEN MAX(CASE WHEN ota.OTA_NAME = 'Direct' THEN ota.RATE_THB END) >
         AVG(CASE WHEN ota.OTA_NAME != 'Direct' THEN ota.RATE_THB END) * 1.1
    THEN 'OVERPRICED'
    ELSE 'AT_PARITY'
  END AS RATE_POSITION,
  COUNT(DISTINCT ota.OTA_NAME) AS OTA_COUNT
FROM RAW.OTA_RATE_FEEDS ota
JOIN RAW.PROPERTIES p ON ota.PROPERTY_ID = p.PROPERTY_ID
GROUP BY p.PROPERTY_ID, p.PROPERTY_NAME, p.DESTINATION, ota.STAY_DATE, ota.ROOM_TYPE;

-- BOOKING_PACE: Booking pace vs same-time-last-year by property
CREATE OR REPLACE DYNAMIC TABLE CURATED.BOOKING_PACE
  TARGET_LAG = '5 minutes'
  WAREHOUSE = TOURISM_WH
AS
WITH current_year AS (
  SELECT
    PROPERTY_ID,
    CHECK_IN,
    BOOKING_DATE,
    COUNT(*) AS BOOKINGS,
    SUM(TOTAL_REVENUE) AS REVENUE,
    SUM(ROOM_NIGHTS) AS ROOM_NIGHTS
  FROM RAW.RESERVATIONS
  WHERE STATUS = 'Confirmed'
    AND CHECK_IN >= DATE_TRUNC('month', CURRENT_DATE())
  GROUP BY PROPERTY_ID, CHECK_IN, BOOKING_DATE
),
prior_year AS (
  SELECT
    PROPERTY_ID,
    DATEADD('year', 1, CHECK_IN) AS CHECK_IN_ADJUSTED,
    DATEADD('year', 1, BOOKING_DATE) AS BOOKING_DATE_ADJUSTED,
    COUNT(*) AS BOOKINGS_STLY,
    SUM(TOTAL_REVENUE) AS REVENUE_STLY,
    SUM(ROOM_NIGHTS) AS ROOM_NIGHTS_STLY
  FROM RAW.RESERVATIONS
  WHERE STATUS = 'Confirmed'
    AND CHECK_IN >= DATEADD('year', -1, DATE_TRUNC('month', CURRENT_DATE()))
    AND CHECK_IN < DATE_TRUNC('month', CURRENT_DATE())
  GROUP BY PROPERTY_ID, DATEADD('year', 1, CHECK_IN), DATEADD('year', 1, BOOKING_DATE)
)
SELECT
  cy.PROPERTY_ID,
  p.PROPERTY_NAME,
  p.DESTINATION,
  cy.CHECK_IN AS STAY_DATE,
  cy.BOOKING_DATE,
  cy.BOOKINGS,
  cy.REVENUE,
  cy.ROOM_NIGHTS,
  COALESCE(py.BOOKINGS_STLY, 0) AS BOOKINGS_STLY,
  COALESCE(py.REVENUE_STLY, 0) AS REVENUE_STLY,
  ROUND(cy.BOOKINGS / NULLIF(py.BOOKINGS_STLY, 0) * 100, 1) AS PACE_INDEX
FROM current_year cy
JOIN RAW.PROPERTIES p ON cy.PROPERTY_ID = p.PROPERTY_ID
LEFT JOIN prior_year py
  ON cy.PROPERTY_ID = py.PROPERTY_ID
  AND cy.CHECK_IN = py.CHECK_IN_ADJUSTED
  AND cy.BOOKING_DATE = py.BOOKING_DATE_ADJUSTED;
