-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Revenue Management & Dynamic Pricing
-- ============================================================================
USE DATABASE TOURISM_REVENUE;
USE SCHEMA ML;

-- ML.FORECAST: Demand forecast by property + source market (14-day horizon)
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.DEMAND_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DEMAND_TIMESERIES'),
  SERIES_COLNAME => 'PROPERTY_MARKET',
  TIMESTAMP_COLNAME => 'FORECAST_DATE',
  TARGET_COLNAME => 'DEMAND_INDEX'
);

CREATE OR REPLACE TABLE ML.DEMAND_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.DEMAND_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: Detect unusual booking pace spikes/drops
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.BOOKING_PACE_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.BOOKING_PACE'),
  SERIES_COLNAME => 'PROPERTY_ID',
  TIMESTAMP_COLNAME => 'STAY_DATE',
  TARGET_COLNAME => 'PACE_INDEX',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.BOOKING_PACE_ANOMALY_RESULTS AS
SELECT * FROM TABLE(
  ML.BOOKING_PACE_ANOMALY!DETECT_ANOMALIES(
    INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.BOOKING_PACE'),
    SERIES_COLNAME => 'PROPERTY_ID',
    TIMESTAMP_COLNAME => 'STAY_DATE',
    TARGET_COLNAME => 'PACE_INDEX'
  )
);
