-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Revenue Management & Dynamic Pricing
-- ============================================================================
USE DATABASE TOURISM_REVENUE;
USE SCHEMA ML;

-- ML.FORECAST: DEMAND_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.DEMAND_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.DEMAND_TIMESERIES'),
  SERIES_COLNAME => 'PROPERTY_MARKET',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.DEMAND_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.DEMAND_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: BOOKING_PACE_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.BOOKING_PACE_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.BOOKING_PACE'),
  SERIES_COLNAME => 'PROPERTY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.BOOKING_PACE_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.BOOKING_PACE_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.BOOKING_PACE'), SERIES_COLNAME => 'PROPERTY_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

