-- ============================================================================
-- 99_RESET.SQL — Reset Revenue Management & Dynamic Pricing to clean demo state
-- ============================================================================
USE DATABASE TOURISM_REVENUE;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_INGEST_OTA_RATES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_RECOMMENDATIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_PUSH_RATES SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.PROPERTY_REVPAR REFRESH;
ALTER DYNAMIC TABLE CURATED.DEMAND_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.RATE_RECOMMENDATIONS REFRESH;
ALTER DYNAMIC TABLE CURATED.BOOKING_PACE REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM TOURISM_REVENUE.RAW.RESERVATIONS → 250000
-- SELECT COUNT(*) FROM TOURISM_REVENUE.RAW.OTA_RATE_FEEDS → 500000
-- SELECT COUNT(*) FROM TOURISM_REVENUE.CURATED.PROPERTY_REVPAR WHERE REVPAR_INDEX < 90 → >20

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_PUSH_RATES RESUME;
ALTER TASK IF EXISTS APP.TASK_GENERATE_RECOMMENDATIONS RESUME;
ALTER TASK IF EXISTS APP.TASK_INGEST_OTA_RATES RESUME;
